<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>chordpro</string>
		<string>chord</string>
		<string>crd</string>
		<string>chpro</string>
		<string>cho</string>
		<string>chopro</string>
		<string>pro</string>
	</array>
	<key>name</key>
	<string>ChordPro</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.chordpro</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.chordpro</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i:(\{)(title|subtitle|composer|artist|album|key|time|tempo|comment_italic|comment|define|textfont|textsize|chordfont|chordsize|columns|page_type|t|st|ci|c|col):(.+)(\}))</string>
			<key>name</key>
			<string>markup.withparams.chordpro</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.chordpro</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i:(\{)(new_song|start_of_chorus|end_of_chorus|start_of_tab|end_of_tab|no_grid|grid|new_page|new_physical_page|column_break|ns|soc|eoc|sob|eob|ng|g|npp|np|colb|col)(\}))</string>
			<key>name</key>
			<string>markup.noparams.chordpro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^#.*$</string>
			<key>name</key>
			<string>comment.chordpro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\[)(.+?)(\])</string>
			<key>name</key>
			<string>keyword.chordpro</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.chordpro</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.function.chordpro</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^([a-gA-G])(\s)*?([\|\-\d\^bs\/])+</string>
			<key>name</key>
			<string>string.chordpro</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.chordpro</string>
	<key>uuid</key>
	<string>74a87291-b181-4071-9a20-2e50d246e5a0</string>
</dict>
</plist>
